services:
  - type: web
    name: stressrice
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    healthCheckPath: /
    autoDeploy: true
